#!/bin/bash
exe_name="$(basename $0)"
functions="git_utils gbranch gpush gpull gmerge gdiff gcheckout"

get_yn() {
   # $1 should be -y or -n
   # $2 should be the yn message
   
   #Get the default yn flag
   default_yn="$(echo ${1:1:1}|tr a-z A-Z)"
   other_yn="$(grep -o "[^$default_yn]" <<< "YN"|tr A-Z a-z)"
   read -p "$2 $other_yn[$default_yn]: " yn
   response_yn="$(echo ${yn}|tr A-Z a-z)"
   # Return if the response was the optional choice 
   # If -y is passed and anything other than N is entered, it will return true
   # If -n is passed and anything other than Y is entered, it will return true
   [ "$other_yn" == "$response_yn" ]
}

master_protect() {
   if [ "$(get_current_branch)" == "master" ]
   then test ! get_yn -n "Are you sure you want to $exe_name in master?"
   fi
}

get_project_name () {
  git remote -v|head -n 1|sed -e 's/.*\/\(.*\)\.git.*/\1/'
}

display_branches () {
   project_name="$(get_project_name)"
   printf "Project: \x1b[32m%s\x1b[0m\n" "$project_name"
   branches=`git branch --list`
   while read -r branch
   do clean_branch_name=${branch//\*\ /}
      description=`git config branch.$clean_branch_name.description`
      if [ "${branch::1}" == "*" ]
      then printf "%-15s %s\n"   "$branch" "$description"
      else printf "  %-13s %s\n" "$branch" "$description"
      fi
   done <<< "$branches"
}

get_current_branch () {
   branches=`git branch --list`
   while read -r branch
   do
      if [ "${branch::1}" == "*" ]
      then clean_branch_name=${branch//\*\ /}
           printf "%s" "$clean_branch_name"
           break
      fi
   done <<< "$branches"
}


# External ref functions
function git_utils() {
   if [ "$1" == "setup" ]
   then echo setting up git_utils
        if [ ! -d ~/bin ]
        then echo making ~/bin
             mkdir -p ~/bin || exit 1
             
        fi
        if [ ! -f ~/bin/git_utils ]
        then echo coping git_utils into ~/bin
             cp $0 ~/bin/git_utils || exit 1
        fi

        if ! grep "$HOME/bin" <<< "$PATH" &> /dev/null && ! grep '^PATH+\?=' ~/.bash_profile|grep '$HOME/bin' &> /dev/null
        then echo 'adding $HOME/bin to $PATH in ~/.bash_profile'
             echo 'PATH+=:$HOME/bin' >> ~/.bash_profile || exit 1
             echo 'export PATH' >> ~/.bash_profile || exit 1
             source ~/.bash_profile || exit 1
        fi
             
        for func in $functions
        do if [ ! -f ~/bin/$func ]
           then ln -s ~/bin/git_utils ~/bin/$func || exit 1
                echo "adding symlink for $func function"
           fi
        done
        echo git_utils should now be available
   else echo "git_utils - Shortcuts for git cli"
        echo 'Usage: git_utils [setup]'
        echo 'Commands provided when setup'
        for func in $functions
        do echo $func
        done
        exit 0
   fi
}        

function gbranch() {
   if [ $# -gt 2 ]
   then echo 'Too Many Parameters. Usage: gbranch [branch_name ["description"]]'
        exit 2
   fi
   
   if [ $# == 0 ]
   then display_branches
   else branch=`get_current_branch`
        if [ "$branch" != "$1" ]
        then if ! git checkout $1 2> /dev/null
             then read -p "Create a new branch $1? [Y/n] " x
                  if [[ "$x" == [Yy] ]]
                  then git checkout -b $1
                       if [ $? -eq 0 ]
                       then if [ "$2" ]
                            then git config branch.$1.description "$2"
                            fi
                       fi
                  fi
             fi
        else if [ "$2" ]
             then git config branch.$1.description "$2"
             fi
        fi
        display_branches
   fi
}

function gpush() {
   branch=$1
   if [ -z "$branch" ]
   then branch="$(get_current_branch)"
   fi
   git push origin $branch
}

function gpull() {
   branch=$1
   if [ -z "$branch" ]
   then branch="$(get_current_branch)"
   fi
   git fetch
   git pull origin $branch
}

function gmerge() {
   if [ $# -ne 1 ]
   then echo 'Invalid parameters. Usage: gmerge branch_name'
        exit 2
   fi
   if master_protect
   then git merge $1
   fi
}

function gdiff() {
   git diff $*
}

function gcheckout() {
   git checkout $*
}


if ! grep -w "$exe_name" <<< "$functions" &> /dev/null
then echo unknown function $exe_name
     exit 1
fi
$exe_name $*
